[package]
name = "null-terminated"
version = "0.2.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "null-terminated arrays"
license = "MIT OR Apache-2.0"

[dependencies]
fallible = "0.1"
idem = "0.3.1"
