[package]
name = "null-terminated"
version = "0.2.6"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "null-terminated arrays"
license = "MIT OR Apache-2.0"

[dependencies]
fallible = "0.1"

[dev-dependencies]
quickcheck = "0.4"
quickcheck_macros = "0.4.2"
